FLASK_APP=app
FLASK_DEBUG=1
FLASK_ENV=development
FLASK_RUN_PORT=5000
# CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
MYSQL_HOST=localhost
MYSQL_PORT=3306
MYSQL_USER=root
MYSQL_PASSWORD=
MYSQL_DB=flask



